# Generated by Django 4.1.3 on 2022-12-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RpsRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('current_user', models.IntegerField()),
                ('maximum_user', models.IntegerField()),
                ('room_state', models.IntegerField()),
                ('host_uuid', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='RpsRooms_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_uuid', models.CharField(max_length=36)),
                ('user_state', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.rpsroom')),
            ],
        ),
    ]
