# Generated by Django 4.1.3 on 2023-01-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0002_rpsrooms_users_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpsrooms_users',
            name='user_host',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
